### ISSUE TITLE
你好，请问预训练需要多大的显存

### ISSUE THREAD

**Issue by allenliuvip** [charent/Phi2-mini-Chinese#1]
rt

**Comment by charent** [comment]
实验性项目，max_len=320，batch_size=8，预训练数据较少。预训练，sft及dpo阶段均为单机单卡，配置如下：
```bash
CPU: Intel(R) i5-13600k @ 5.1GHz
内存：32 GB
显卡：NVIDIA GeForce RTX 4060 Ti 16GB * 1
```

**Comment by DumoeDss** [comment]
请问该配置训练用了多长时间？

**Comment by charent** [comment]
预训练我跑了4-5天，sft跑了一天，rlhf跑了半天好像。大差不差吧，我后面换过数据集，有点忘了。

**Comment by zhilangtaosha** [comment]
4060没ti 能训练吗  只有8GB 显存

**Comment by WindBruce** [comment]
你好，这个[tokeinzer](https://github.com/charent/Phi2-mini-Chinese/blob/main/1.tokeinzer.ipynb)，我看你是用cpu再训练，这个不能用显卡加速吗？

**Comment by charent** [comment]
不能用显卡加速，tokenizer训练主要是对txt语料做char/byte级别的分割、统计、合并操作，本质上是对字符串进行操作，不是对float/int类型的向量、矩阵进行操作。

**Comment by Muzych** [comment]
mac mini m4 16G能训练吗
