### ISSUE TITLE
model_save路径不存在

### ISSUE THREAD

**Issue by hulonghua-devin** [charent/Phi2-mini-Chinese#11]
老铁，你好。

我尝试使用你代码预训练的时候发现没有model_save路径。

tokenizer_dir: str = './model_save/tokenizer/'

请问model_save下面的内容是自己训练的？ 有没有一句训练好的tokenizer？

**Comment by charent** [comment]
你用main分支的代码吧。`model_save`文件夹是要自己创建的，`tokenizer`不想自己训练的话，可以去hf仓库下载：[Phi2-Chinese-0.2B](https://huggingface.co/charent/Phi2-Chinese-0.2B)，`tokenizer_dir`设置成模型文件一样的路径就行了，比如：[6.1 普通对话能力](https://github.com/charent/Phi2-mini-Chinese/tree/main?tab=readme-ov-file#61-%E6%99%AE%E9%80%9A%E5%AF%B9%E8%AF%9D%E8%83%BD%E5%8A%9B)

**Comment by hulonghua-devin** [comment]
好的，感谢！
