### ISSUE TITLE
预训练数据集问题

### ISSUE THREAD

**Issue by lxianl455** [charent/Phi2-mini-Chinese#12]
请问使用的预训练数据集是什么？ 我去BELLE仓库去看，看到的大多数都是指令微调的数据集。你是使用类似于[Multiturn Chat](https://huggingface.co/datasets/BelleGroup/multiturn_chat_0.8M)这种数据集去做预训练的吗？

**Comment by charent** [comment]
现在huggingface发布的版本中，有添加过单论对话的语料，多轮对话的语料没有添加
