### ISSUE TITLE
关于c eavl的结果

### ISSUE THREAD

**Issue by lxianl455** [charent/Phi2-mini-Chinese#13]
![image](https://github.com/charent/Phi2-mini-Chinese/assets/63391363/798877f7-e44c-405c-999b-8b8f8c161fd8)
大佬，ceavl的结果我看网上的好像说，因为是单选题，所以随机选择是1/4的几率。这个结果上看来是不是就第一个是超过了随机选择的结果。 没别的意思，我就是想知道这样分析结果对不对。

**Comment by charent** [comment]
超过这几分聊胜于无吧，一般来说，小模型超过十几分才有参考价值
