### ISSUE TITLE
能更換模型架構嗎?

### ISSUE THREAD

**Issue by win10ogod** [charent/Phi2-mini-Chinese#14]
能使用deepseek-v2或是llama3 的模型架構嗎?

**Comment by win10ogod** [comment]
@charent 打擾你了但真的很好奇

**Comment by charent** [comment]
请参考这个项目：[Phi2-mini-Chinese](https://github.com/charent/Phi2-mini-Chinese/tree/dev)，将模型替换为你自己定义的模型即可：[pre_train.py#L174](https://github.com/charent/Phi2-mini-Chinese/blob/c7276970d91f53019a474bdbaefc9e97af72bec5/train_model/pre_train.py#L174)
