### ISSUE TITLE
请问对应的资源文件要去哪里获取呢?

### ISSUE THREAD

**Issue by cjxx2016** [charent/Phi2-mini-Chinese#2]
这是个很棒的项目, 我在代码中看到 ./data/wiki.simple.txt, 等资源数据文件, 是否有对应的说明和获取方式呢?

**Comment by charent** [comment]
详细的数据清洗过程在我的另外一个项目，[raw_data_process.py#L599](https://github.com/charent/ChatLM-mini-Chinese/blob/02ace3ce1b45011f957e8d3a57e1f3f126ee6bb3/utils/raw_data_process.py#L599)。

自己也可以去wiki 下载地址：<https://dumps.wikimedia.org/zhwiki/>， 将下载的bz2文件转换为wiki.txt参考：，<https://github.com/apertium/WikiExtractor>，最后利用`OpenCC`库转换为简体中文就是了。

**Comment by cjxx2016** [comment]
了解了, 谢谢解答~
