### ISSUE TITLE
好奇问下为什么叫Phi2？

### ISSUE THREAD

**Issue by yucc-leon** [charent/Phi2-mini-Chinese#3]
Phi系列的主要贡献是用了据说是教科书级数据训练，核心技术在怎么做教科书级的数据库。作者采用Phi命名的原因是什么呢？

**Comment by charent** [comment]
我使用了`huggingface transfomers`的`PhiForCausalLM`，`PhiForCausalLM`这个类是在`phi2`发布后不久引入的，所以我就直接用了`phi2`来命名项目。我在`readme.md`中也提到，这是一个实验性项目，所以命名也没有什么严格的规范。

当然，不可否认phi2系列对优质数据集探索的贡献。本项目也尝试对优质的中文数据集进行探索（主要是百科数据，如：wiki、百度百科），在`dev`分支已经提交了好几版的数据集处理的代码。

**Comment by yucc-leon** [comment]
好的感谢~
